# Generated by Django 5.2.7 on 2025-11-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_account_id_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
