# Generated by Django 5.2.7 on 2025-11-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_account_accountid_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
    ]
