# Generated by Django 5.2.7 on 2025-11-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_account_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creator_id',
            field=models.IntegerField(),
        ),
    ]
