# Generated by Django 5.2.7 on 2025-11-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_account_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
