# Generated by Django 5.2.7 on 2025-11-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(default='STUDENT', max_length=50),
        ),
    ]
